In [11]:
# feature engineering

In [12]:
import pandas as pd

In [13]:
# df=pd.read_csv('C:/Users/swapn/Loan-Approval-Prediction/data/Loan_Approval_Prediction.csv')
import joblib
df=joblib.load('../learning_notebooks/data/df.pkl')

In [14]:
df.head()

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh
0,1,5849,0,146,360,1,5849,0,0,0,0,0,0,0,1,0,0,1
1,1,4583,1508,128,360,1,6091,0,1,1,0,0,0,0,0,0,0,1
2,1,3000,0,66,360,1,3000,0,1,0,0,0,0,1,1,1,0,0
3,1,2583,2358,120,360,1,4941,0,1,0,0,0,1,0,1,0,1,0
4,1,6000,0,141,360,1,6000,0,0,0,0,0,0,0,1,0,0,1

In [15]:
df.isnull().sum()

Gender                    0
ApplicantIncome           0
CoapplicantIncome         0
Loan_Amount               0
Loan_Amount_Term          0
Credit_History            0
TotalIncome               0
LoanIncomeRatio           0
Married_Yes               0
Dependents_1              0
Dependents_2              0
Dependents_3+             0
Education_Not Graduate    0
Self_Employed_Yes         0
Loan_Status_Y             0
IncomeGroup_medium        0
IncomeGroup_high          0
IncomeGroup_veryhigh      0
dtype: int64

In [16]:
# 1) handle missing value
df['Loan_Amount']=df['Loan_Amount'].fillna(df['Loan_Amount'].median())

In [17]:
# bining
df['ApplicantIncome_Group']=pd.cut(df['ApplicantIncome'],bins=5)

In [18]:
# log transformation
import numpy as np
df['Loan_Amount_log']=np.log1p(df['Loan_Amount'])

In [19]:
# interaction feature 
df['TotalIncome']=df['ApplicantIncome'] + df['CoapplicantIncome']

In [20]:
df

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,ApplicantIncome_Group,Loan_Amount_log
0,1,5849,0,146,360,1,5849,0,0,0,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",4.990433
1,1,4583,1508,128,360,1,6091,0,1,1,0,0,0,0,0,0,0,1,"(69.15, 16320.0]",4.859812
2,1,3000,0,66,360,1,3000,0,1,0,0,0,0,1,1,1,0,0,"(69.15, 16320.0]",4.204693
3,1,2583,2358,120,360,1,4941,0,1,0,0,0,1,0,1,0,1,0,"(69.15, 16320.0]",4.795791
4,1,6000,0,141,360,1,6000,0,0,0,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",4.955827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,2900,0,71,360,1,2900,0,0,0,0,0,0,0,1,1,0,0,"(69.15, 16320.0]",4.276666
610,1,4106,0,40,180,1,4106,0,1,0,0,1,0,0,1,0,1,0,"(69.15, 16320.0]",3.713572
611,1,8072,240,253,360,1,8312,0,1,1,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",5.537334
612,1,7583,0,187,360,1,7583,0,1,0,1,0,0,0,1,0,0,1,"(69.15, 16320.0]",5.236442
613,0,4583,0,133,360,0,4583,0,0,0,0,0,0,1,0,0,1,0,"(69.15, 16320.0]",4.897840

In [21]:
# encoding and scaling

In [22]:
# # encoding 
# # label Encoding 
# from sklearn.preprocessing import LabelEncoder
# le=LabelEncoder()
# df['Education']=le.fit_transform(df['Education'])

In [23]:
# # one hot encoding 
# df[['Education','Gender','Married']]=pd.get_dummies(df[['Education','Gender','Married']],drop_first=True).astype(int)

In [24]:
df

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,ApplicantIncome_Group,Loan_Amount_log
0,1,5849,0,146,360,1,5849,0,0,0,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",4.990433
1,1,4583,1508,128,360,1,6091,0,1,1,0,0,0,0,0,0,0,1,"(69.15, 16320.0]",4.859812
2,1,3000,0,66,360,1,3000,0,1,0,0,0,0,1,1,1,0,0,"(69.15, 16320.0]",4.204693
3,1,2583,2358,120,360,1,4941,0,1,0,0,0,1,0,1,0,1,0,"(69.15, 16320.0]",4.795791
4,1,6000,0,141,360,1,6000,0,0,0,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",4.955827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,2900,0,71,360,1,2900,0,0,0,0,0,0,0,1,1,0,0,"(69.15, 16320.0]",4.276666
610,1,4106,0,40,180,1,4106,0,1,0,0,1,0,0,1,0,1,0,"(69.15, 16320.0]",3.713572
611,1,8072,240,253,360,1,8312,0,1,1,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",5.537334
612,1,7583,0,187,360,1,7583,0,1,0,1,0,0,0,1,0,0,1,"(69.15, 16320.0]",5.236442
613,0,4583,0,133,360,0,4583,0,0,0,0,0,0,1,0,0,1,0,"(69.15, 16320.0]",4.897840

In [25]:
# # scaling
# from sklearn.preprocessing import StandardScaler
# scaler=StandardScaler()
# X_train_scaled=scaler.fit(X_train)
# X_test_scaled=scaler.transform(X_test)

In [26]:
X=df.drop('Loan_Status_Y',axis=1)
y=df['Loan_Status_Y']

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
# # scaling
# from sklearn.preprocessing import StandardScaler
# scaler=StandardScaler()
# X_train_scaled=scaler.fit(X_train)
# X_test_scaled=scaler.transform(X_test)

In [29]:
df

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,ApplicantIncome_Group,Loan_Amount_log
0,1,5849,0,146,360,1,5849,0,0,0,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",4.990433
1,1,4583,1508,128,360,1,6091,0,1,1,0,0,0,0,0,0,0,1,"(69.15, 16320.0]",4.859812
2,1,3000,0,66,360,1,3000,0,1,0,0,0,0,1,1,1,0,0,"(69.15, 16320.0]",4.204693
3,1,2583,2358,120,360,1,4941,0,1,0,0,0,1,0,1,0,1,0,"(69.15, 16320.0]",4.795791
4,1,6000,0,141,360,1,6000,0,0,0,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",4.955827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,2900,0,71,360,1,2900,0,0,0,0,0,0,0,1,1,0,0,"(69.15, 16320.0]",4.276666
610,1,4106,0,40,180,1,4106,0,1,0,0,1,0,0,1,0,1,0,"(69.15, 16320.0]",3.713572
611,1,8072,240,253,360,1,8312,0,1,1,0,0,0,0,1,0,0,1,"(69.15, 16320.0]",5.537334
612,1,7583,0,187,360,1,7583,0,1,0,1,0,0,0,1,0,0,1,"(69.15, 16320.0]",5.236442
613,0,4583,0,133,360,0,4583,0,0,0,0,0,0,1,0,0,1,0,"(69.15, 16320.0]",4.897840

In [30]:
# pipe line

In [31]:
# pipeline for use seperate num,cat column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [32]:
# Pipeline 
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

num_feature=['CoapplicantIncome','ApplicantIncome']
cat_feature=['Gender', 'Married_Yes', 'Education_Not Graduate']

preprocess=ColumnTransformer([
    ('num',StandardScaler(),num_feature),
    ('cat',OneHotEncoder(),cat_feature)
])

model=Pipeline([
    ('preprocess',preprocess),
    ('classifier',LogisticRegression())
])
model.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CoapplicantIncome',
                                                   'ApplicantIncome']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Gender', 'Married_Yes',
                                                   'Education_Not '
                                                   'Graduate'])])),
                ('classifier', LogisticRegression())])

In [33]:
# pipeline with randomfrorest
from sklearn.ensemble import RandomForestClassifier
rf_model=Pipeline([
    ('preprocess',preprocess), 
    ('classifier',RandomForestClassifier(
        n_estimators=200, 
        random_state=42
    ))
])
rf_model.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CoapplicantIncome',
                                                   'ApplicantIncome']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Gender', 'Married_Yes',
                                                   'Education_Not '
                                                   'Graduate'])])),
                ('classifier',
                 RandomForestClassifier(n_estimators=200, random_state=42))])

In [34]:
# gridsearch with pipeline 
from sklearn.model_selection import GridSearchCV
param_grid={
    'classifier__n_estimators':[100,200], 
    'classifier__max_depth':[5,10]
}
grid=GridSearchCV(
    rf_model, 
    param_grid,
    cv=5,
    scoring='f1'
)
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['CoapplicantIncome',
                                                                          'ApplicantIncome']),
                                                                        ('cat',
                                                                         OneHotEncoder(),
                                                                         ['Gender',
                                                                          'Married_Yes',
                                                                          'Education_Not '
                                                                          'Graduate'])])),
                                       ('classifier',
                                        RandomForestClassifier(n_estimators=200,
                                                               random_state=42))]),
             param_grid={'classifier__max_depth': [5, 10],
                         'classifier__n_estimators': [100, 200]},
             scoring='f1')