In [17]:
import joblib
df = joblib.load("../learning_notebooks/data/df.pkl")
rf_model = joblib.load("../learning_notebooks/model/rf_model.pkl")

In [18]:
df

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh
0,1,5849,0,146,360,1,5849,0,0,0,0,0,0,0,1,0,0,1
1,1,4583,1508,128,360,1,6091,0,1,1,0,0,0,0,0,0,0,1
2,1,3000,0,66,360,1,3000,0,1,0,0,0,0,1,1,1,0,0
3,1,2583,2358,120,360,1,4941,0,1,0,0,0,1,0,1,0,1,0
4,1,6000,0,141,360,1,6000,0,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,2900,0,71,360,1,2900,0,0,0,0,0,0,0,1,1,0,0
610,1,4106,0,40,180,1,4106,0,1,0,0,1,0,0,1,0,1,0
611,1,8072,240,253,360,1,8312,0,1,1,0,0,0,0,1,0,0,1
612,1,7583,0,187,360,1,7583,0,1,0,1,0,0,0,1,0,0,1
613,0,4583,0,133,360,0,4583,0,0,0,0,0,0,1,0,0,1,0

In [19]:
X=df.drop('Loan_Status_Y',axis=1)
y=df['Loan_Status_Y']

In [20]:
# cross validation

In [21]:
# k fold code 
from sklearn.model_selection import cross_val_score
score=cross_val_score(
    rf_model, 
    X,
    y,
    cv=5, 
    scoring='f1'
)

In [22]:
score

array([0.84324324, 0.8172043 , 0.86021505, 0.84393064, 0.86666667])

In [23]:
score.mean()

np.float64(0.846251980117354)

In [24]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [25]:
skf

StratifiedKFold(n_splits=5, random_state=42, shuffle=True)

In [26]:
# learning curve

In [27]:
# plot learning curve

In [28]:
from sklearn.model_selection import learning_curve
import numpy as np
train_sizes,train_score,val_score=learning_curve(
    rf_model, 
    X, 
    y, 
    cv=5, 
    scoring='f1', 
    train_sizes=np.linspace(0.1,1.0,5)
)
train_mean=train_score.mean(axis=1) 
val_mean=val_score.mean(axis=1)

In [29]:
train_mean

array([1., 1., 1., 1., 1.])

In [30]:
val_mean

array([0.81397252, 0.82853299, 0.82877917, 0.85331868, 0.84498569])

In [32]:
print(val_mean)

[0.81397252 0.82853299 0.82877917 0.85331868 0.84498569]

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
# prediction 
rf_model.fit(X_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [43]:
# prediction 
y_pred_rf=rf_model.predict(X_test)

In [44]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_rf)
cm

array([[21, 22],
       [ 6, 74]])

In [45]:
# analyze the false positive and false negative 
X_test_copy=X_test.copy()
X_test_copy['actual']=y_test.values
X_test_copy['predicted']=y_pred_rf

false_positive=X_test_copy[
    (X_test_copy['actual']==0)&(X_test_copy['predicted']==1)
]

false_negative=X_test_copy[
    (X_test_copy['actual']==1)&(X_test_copy['predicted']==0)
]

In [46]:
false_positive

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,actual,predicted
340,1,2647,1587,173,360,1,4234,0,1,0,0,1,1,0,0,1,0,0,1
77,1,1000,3022,110,360,1,4022,0,1,1,0,0,0,1,0,1,0,0,1
148,0,10000,1666,225,360,1,11666,0,0,0,0,0,0,0,0,0,0,0,1
457,1,3708,2569,173,360,1,6277,0,1,0,0,0,0,0,0,0,1,0,1
82,0,1378,1881,167,360,1,3259,0,1,0,1,0,0,0,0,1,0,0,1
319,1,10000,0,155,360,1,10000,0,1,1,0,0,0,1,0,0,1,0,1
30,1,4166,3369,201,360,1,7535,0,1,1,0,0,0,0,0,0,1,0,1
210,0,10000,0,214,360,1,10000,0,0,0,0,0,0,0,0,0,1,0,1
519,0,3400,0,95,360,1,3400,0,0,0,0,0,1,0,0,1,0,0,1
76,1,3750,4750,176,360,1,8500,0,0,0,0,0,0,0,0,0,1,0,1
24,1,3717,2925,151,360,1,6642,0,1,1,0,0,0,1,0,0,1,0,1
257,1,5250,0,94,360,1,5250,0,1,0,0,1,0,0,0,0,1,0,1
192,1,6033,0,160,360,1,6033,0,1,0,0,0,1,0,0,0,1,0,1
174,1,4344,736,87,360,1,5080,0,1,0,0,0,1,1,0,0,1,0,1
140,1,5042,2083,185,360,1,7125,0,1,0,1,0,0,0,0,0,1,0,1
63,1,4945,0,146,360,0,4945,0,1,1,0,0,0,0,0,1,0,0,1
469,1,4333,2451,110,360,1,6784,0,1,0,0,0,0,0,0,0,1,0,1
574,1,6406,0,150,360,1,6406,0,1,0,0,1,0,0,0,0,1,0,1
284,1,20667,0,146,360,1,20667,0,1,0,0,0,0,0,0,0,0,0,1
135,1,4000,7750,290,360,1,11750,0,1,0,0,1,0,0,0,0,0,0,1
181,1,1916,5063,67,360,1,6979,0,0,0,0,0,0,0,0,0,1,0,1
118,1,5568,2142,175,360,1,7710,0,1,0,0,0,0,0,0,0,1,0,1

In [47]:
false_negative

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,actual,predicted
182,1,4600,0,73,180,1,4600,0,1,0,0,0,0,0,0,1,0,1,0
228,1,4758,0,158,480,1,4758,0,0,0,0,0,0,0,0,1,0,1,0
155,1,39999,0,600,180,0,39999,0,1,0,0,1,0,0,0,0,0,1,0
81,1,2395,0,146,360,1,2395,0,1,1,0,0,0,1,1,0,0,1,0
72,1,3500,0,81,300,1,3500,0,0,0,0,0,0,0,0,1,0,1,0
42,1,2400,0,75,360,1,2400,0,1,0,0,0,0,0,1,0,0,1,0

In [48]:
# predict probablit
y_prob=rf_model.predict_proba(X_test)[:,1]

In [55]:
# change probability for reduce false postive 
custom_y_pred=(y_prob>=0.6).astype(int)

In [56]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,custom_y_pred)
cm

array([[23, 20],
       [ 9, 71]])

In [57]:
# analyze the false positive and false negative 
X_test_copy=X_test.copy()
X_test_copy['actual']=y_test.values
X_test_copy['predicted']=custom_y_pred

false_positive=X_test_copy[
    (X_test_copy['actual']==0)&(X_test_copy['predicted']==1)
]

false_negative=X_test_copy[
    (X_test_copy['actual']==1)&(X_test_copy['predicted']==0)
]

In [58]:
false_positive

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,actual,predicted
340,1,2647,1587,173,360,1,4234,0,1,0,0,1,1,0,0,1,0,0,1
77,1,1000,3022,110,360,1,4022,0,1,1,0,0,0,1,0,1,0,0,1
148,0,10000,1666,225,360,1,11666,0,0,0,0,0,0,0,0,0,0,0,1
457,1,3708,2569,173,360,1,6277,0,1,0,0,0,0,0,0,0,1,0,1
319,1,10000,0,155,360,1,10000,0,1,1,0,0,0,1,0,0,1,0,1
30,1,4166,3369,201,360,1,7535,0,1,1,0,0,0,0,0,0,1,0,1
210,0,10000,0,214,360,1,10000,0,0,0,0,0,0,0,0,0,1,0,1
519,0,3400,0,95,360,1,3400,0,0,0,0,0,1,0,0,1,0,0,1
76,1,3750,4750,176,360,1,8500,0,0,0,0,0,0,0,0,0,1,0,1
24,1,3717,2925,151,360,1,6642,0,1,1,0,0,0,1,0,0,1,0,1
257,1,5250,0,94,360,1,5250,0,1,0,0,1,0,0,0,0,1,0,1
192,1,6033,0,160,360,1,6033,0,1,0,0,0,1,0,0,0,1,0,1
174,1,4344,736,87,360,1,5080,0,1,0,0,0,1,1,0,0,1,0,1
140,1,5042,2083,185,360,1,7125,0,1,0,1,0,0,0,0,0,1,0,1
469,1,4333,2451,110,360,1,6784,0,1,0,0,0,0,0,0,0,1,0,1
574,1,6406,0,150,360,1,6406,0,1,0,0,1,0,0,0,0,1,0,1
284,1,20667,0,146,360,1,20667,0,1,0,0,0,0,0,0,0,0,0,1
135,1,4000,7750,290,360,1,11750,0,1,0,0,1,0,0,0,0,0,0,1
181,1,1916,5063,67,360,1,6979,0,0,0,0,0,0,0,0,0,1,0,1
118,1,5568,2142,175,360,1,7710,0,1,0,0,0,0,0,0,0,1,0,1

In [59]:
false_negative

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,actual,predicted
109,1,2071,754,94,480,1,2825,0,1,0,0,1,1,0,1,0,0,1,0
182,1,4600,0,73,180,1,4600,0,1,0,0,0,0,0,0,1,0,1,0
228,1,4758,0,158,480,1,4758,0,0,0,0,0,0,0,0,1,0,1,0
155,1,39999,0,600,180,0,39999,0,1,0,0,1,0,0,0,0,0,1,0
81,1,2395,0,146,360,1,2395,0,1,1,0,0,0,1,1,0,0,1,0
72,1,3500,0,81,300,1,3500,0,0,0,0,0,0,0,0,1,0,1,0
473,0,2500,0,93,360,1,2500,0,0,0,0,0,0,1,1,0,0,1,0
42,1,2400,0,75,360,1,2400,0,1,0,0,0,0,0,1,0,0,1,0
248,1,2882,1843,123,480,1,4725,0,1,1,0,0,0,0,0,1,0,1,0

In [60]:
# segment base error analysis
high_loan=false_positive[false_positive['Loan_Amount']>200]

In [61]:
high_loan

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh,actual,predicted
148,0,10000,1666,225,360,1,11666,0,0,0,0,0,0,0,0,0,0,0,1
30,1,4166,3369,201,360,1,7535,0,1,1,0,0,0,0,0,0,1,0,1
210,0,10000,0,214,360,1,10000,0,0,0,0,0,0,0,0,0,1,0,1
135,1,4000,7750,290,360,1,11750,0,1,0,0,1,0,0,0,0,0,0,1

In [64]:
cost=(false_positive*10)+(false_negative*3)